# Generated by Django 2.1 on 2020-07-11 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('imdb_score', models.FloatField()),
                ('director', models.CharField(max_length=50)),
                ('popularity', models.FloatField()),
                ('genre', models.CharField(max_length=20)),
            ],
        ),
    ]
