# Generated by Django 2.1 on 2020-07-11 06:22

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('Movies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='genre',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Adventure', 'Adventure'), ('Family', 'Family'), ('Fantasy', 'Fantasy'), ('Musical', 'Musical'), ('Suspense', 'Suspense'), ('Drama', 'Drama')], max_length=20),
        ),
    ]
