# Generated by Django 2.1 on 2020-07-12 18:37

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('Movies', '0005_auto_20200712_1759'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='genre',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Adventure', 'Adventure'), ('Family', 'Family'), ('Fantasy', 'Fantasy'), ('Musical', 'Musical'), ('Suspense', 'Suspense'), ('Drama', 'Drama'), ('Sci-Fi', 'Sci-Fi'), ('Action', 'Action'), ('Mystrey', 'Mystrey')], max_length=100),
        ),
    ]
